GET http://localhost:3000/index

###

GET http://localhost:3000/index/608de3462898a3090877d2dc

###

POST  http://localhost:3000/index
Content-Type: application/json

{
    "firstname": "Leo",
    "lastname": "Aman",
    "username": "leo",
    "password": "123"
}

###

DELETE http://localhost:3000/index/608ddf376845693cb044a122

###

PATCH http://localhost:3000/index/608de997a9558332781b07ee
Content-Type: application/json

{
    "firstname": "anca"
}

